/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunHistoryRouteImport } from './routes/run-history'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LedgersRouteImport } from './routes/ledgers'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as IndexRouteImport } from './routes/index'

const RunHistoryRoute = RunHistoryRouteImport.update({
  id: '/run-history',
  path: '/run-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgersRoute = LedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRoute
  '/ledgers': typeof LedgersRoute
  '/portfolio': typeof PortfolioRoute
  '/run-history': typeof RunHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRoute
  '/ledgers': typeof LedgersRoute
  '/portfolio': typeof PortfolioRoute
  '/run-history': typeof RunHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRoute
  '/ledgers': typeof LedgersRoute
  '/portfolio': typeof PortfolioRoute
  '/run-history': typeof RunHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/earnings' | '/ledgers' | '/portfolio' | '/run-history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/earnings' | '/ledgers' | '/portfolio' | '/run-history'
  id:
    '__root__' | '/' | '/earnings' | '/ledgers' | '/portfolio' | '/run-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarningsRoute: typeof EarningsRoute
  LedgersRoute: typeof LedgersRoute
  PortfolioRoute: typeof PortfolioRoute
  RunHistoryRoute: typeof RunHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/run-history': {
      id: '/run-history'
      path: '/run-history'
      fullPath: '/run-history'
      preLoaderRoute: typeof RunHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledgers': {
      id: '/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof LedgersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarningsRoute: EarningsRoute,
  LedgersRoute: LedgersRoute,
  PortfolioRoute: PortfolioRoute,
  RunHistoryRoute: RunHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
