// Renders a resolved egress allowlist (egress-allowlist.ts) into the two config artifacts #7857's real
// enforcement needs: dnsmasq config text, and an iptables/ipset ruleset. Pure text generation, no IO -- the
// thin shell entrypoint (egress-firewall-entrypoint.sh) writes this output to disk and applies it.
//
// MECHANISM: dnsmasq is this container's ONLY permitted DNS resolver, configured with one `ipset=/host/set`
// directive per allowed hostname -- dnsmasq's own well-established feature where resolving a matched domain for
// ANY caller also adds the resolved IP to the named ipset automatically, in-band with the real lookup (no
// separate polling/refresh needed to track IP rotation on CDN-backed hosts like registry.npmjs.org). iptables
// then: (1) defaults OUTPUT to DROP, (2) allows loopback (dnsmasq itself, local IPC), (3) allows outbound DNS
// (port 53) ONLY to the upstream resolvers dnsmasq itself is configured to forward to -- forcing every domain
// lookup through the controlled resolver, since a subprocess trying to query a DIFFERENT DNS server directly
// is blocked before dnsmasq ever gets a chance to populate the ipset for it, and (4) allows outbound traffic to
// any IP already in the ipset, on standard ports. This is the well-established, standard Linux pattern for
// domain-based (not just IP-based) firewall allowlisting -- not a novel design.
//
// Every hostname is re-validated against the RFC 1123 shape (same regex ams-policy-spec.ts's own parser already
// enforces on `extraHosts`) immediately before it reaches this shell-adjacent text -- defense in depth: this
// module's own correctness must not depend on every future caller re-verifying its inputs were pre-sanitized
// upstream.
import type { EgressAllowlistEntry } from "./egress-allowlist.js";

export const EGRESS_IPSET_NAME = "loopover_egress_allow";
export const EGRESS_ALLOWED_TCP_PORTS = [80, 443, 22] as const;

// Same shape as ams-policy-spec.ts's own HOSTNAME_RE (kept independent rather than imported -- that file lives
// in @loopover/engine and validates operator input at parse time; this one is the last line of defense right
// before generating shell-adjacent config text, and must keep working even if that upstream check ever changes).
const HOSTNAME_RE = /^(?=.{1,253}$)(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)*[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$/;

export class InvalidEgressHostError extends Error {
  constructor(host: string) {
    super(`Refusing to generate egress-firewall config for an invalid hostname: ${JSON.stringify(host)}`);
    this.name = "InvalidEgressHostError";
  }
}

function assertValidHosts(entries: readonly EgressAllowlistEntry[]): void {
  for (const entry of entries) {
    if (!HOSTNAME_RE.test(entry.host)) throw new InvalidEgressHostError(entry.host);
  }
}

/** The `LOOPOVER_MINER_DISABLE_EGRESS_FIREWALL` no-op ruleset (#7857's documented escape hatch): applies no
 *  restriction at all, for an operator who hit a real snag and needs to get unblocked before fixing their
 *  `networkAllowlist` properly and removing the override. */
export function renderDisabledRuleset(): string {
  return ["#!/bin/sh", "# Generated by egress-firewall-config.ts -- do not edit by hand.", "# LOOPOVER_MINER_DISABLE_EGRESS_FIREWALL is set -- no network-egress restriction applied.", "exit 0", ""].join("\n");
}

/** Render dnsmasq config: one `ipset=/host/setname` directive per allowed hostname, plus `server=` lines for
 *  the upstream resolvers it forwards real lookups to. Deliberately does NOT set `no-resolv`/read
 *  `/etc/resolv.conf` -- the upstream servers are pinned explicitly so the iptables ruleset below can allow
 *  dnsmasq's own outbound DNS to those EXACT, known destinations rather than an open-ended "wherever
 *  /etc/resolv.conf happens to point." */
export function renderDnsmasqConfig(entries: readonly EgressAllowlistEntry[], upstreamResolvers: readonly string[] = ["1.1.1.1", "8.8.8.8"]): string {
  assertValidHosts(entries);
  const lines = [
    "# Generated by egress-firewall-config.ts -- do not edit by hand.",
    "port=53",
    "bind-interfaces",
    "listen-address=127.0.0.1",
    "no-resolv",
    ...upstreamResolvers.map((server) => `server=${server}`),
    ...entries.map((entry) => `ipset=/${entry.host}/${EGRESS_IPSET_NAME}`),
  ];
  return `${lines.join("\n")}\n`;
}

/** Render the iptables/ipset ruleset as a plain shell script body (a sequence of `ipset`/`iptables` invocations,
 *  not a single ip(6)tables-restore blob, so the entrypoint can surface exactly which command failed). Deny-by-
 *  default OUTPUT; the RETURN value is meant to be written to a file and `source`d (or piped to `sh`) by the
 *  entrypoint as root, before dropping to the `node` user. */
export function renderIptablesRuleset(entries: readonly EgressAllowlistEntry[], upstreamResolvers: readonly string[] = ["1.1.1.1", "8.8.8.8"]): string {
  assertValidHosts(entries);
  const lines = [
    "#!/bin/sh",
    "# Generated by egress-firewall-config.ts -- do not edit by hand.",
    "set -eu",
    "",
    `ipset create ${EGRESS_IPSET_NAME} hash:ip -exist`,
    "",
    "iptables -F OUTPUT",
    "iptables -P OUTPUT DROP",
    "",
    "# Loopback: dnsmasq itself, local IPC.",
    "iptables -A OUTPUT -o lo -j ACCEPT",
    "",
    "# DNS to the exact upstream resolvers dnsmasq forwards to, and nowhere else -- forces every lookup",
    "# through dnsmasq, which is the only thing that ever adds an IP to the allow ipset.",
    ...upstreamResolvers.flatMap((server) => [
      `iptables -A OUTPUT -p udp -d ${server} --dport 53 -j ACCEPT`,
      `iptables -A OUTPUT -p tcp -d ${server} --dport 53 -j ACCEPT`,
    ]),
    "",
    "# Egress to anything dnsmasq has already resolved for an allowed hostname, on standard ports.",
    ...EGRESS_ALLOWED_TCP_PORTS.map((port) => `iptables -A OUTPUT -m set --match-set ${EGRESS_IPSET_NAME} dst -p tcp --dport ${port} -j ACCEPT`),
    "",
    `# Allowed hosts (${entries.length}): ${entries.map((entry) => `${entry.host} [${entry.reason}]`).join(", ") || "(none -- OS registries and target-repo-git-remote hosts are always present, so this should never be empty)"}`,
  ];
  return `${lines.join("\n")}\n`;
}
