import { describe, expect, it } from "vitest";

import { formStateToYaml, type GeneratorFormState } from "@/lib/config-generator-yaml";

const HEADER = "# .loopover.yml — generated by the config generator";

describe("formStateToYaml", () => {
  it("serializes a full gate.aiReview config with every field set", () => {
    const state: GeneratorFormState = {
      gate: {
        aiReview: {
          combine: "consensus",
          provider: "anthropic",
          model: "claude-3-5-sonnet-latest",
        },
      },
    };
    expect(formStateToYaml(state)).toBe(
      [
        HEADER,
        "gate:",
        "  aiReview:",
        "    combine: consensus",
        "    provider: anthropic",
        "    model: claude-3-5-sonnet-latest",
      ].join("\n"),
    );
  });

  it("omits unset keys for a partial config (only provider set)", () => {
    const state: GeneratorFormState = { gate: { aiReview: { provider: "openai" } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", "    provider: openai"].join("\n"),
    );
  });

  it("omits unset keys for a partial config (only combine and model set)", () => {
    const state: GeneratorFormState = { gate: { aiReview: { combine: "single", model: "gpt-5" } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", "    combine: single", "    model: gpt-5"].join("\n"),
    );
  });

  it("emits only the header for a fully empty state", () => {
    expect(formStateToYaml({})).toBe(HEADER);
  });

  it("emits only the header when gate is present but aiReview is unset", () => {
    expect(formStateToYaml({ gate: {} })).toBe(HEADER);
  });

  it("treats null fields the same as unset (omitted, not emitted as `null`)", () => {
    const state: GeneratorFormState = {
      gate: { aiReview: { combine: null, provider: null, model: null } },
    };
    expect(formStateToYaml(state)).toBe(HEADER);
  });

  it("treats an empty-string model as unset rather than emitting a blank value", () => {
    const state: GeneratorFormState = { gate: { aiReview: { provider: "anthropic", model: "" } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", "    provider: anthropic"].join("\n"),
    );
  });

  it("quotes a model value containing YAML-special characters", () => {
    const state: GeneratorFormState = { gate: { aiReview: { model: "claude: sonnet" } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", `    model: ${JSON.stringify("claude: sonnet")}`].join("\n"),
    );
  });

  it("quotes a model value with leading/trailing whitespace", () => {
    const state: GeneratorFormState = { gate: { aiReview: { model: " claude " } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", `    model: ${JSON.stringify(" claude ")}`].join("\n"),
    );
  });

  // Regression (#7786): an embedded newline is not caught by trim() (which only strips edges) and is
  // none of the flagged special chars, so the old guard emitted it as a raw multi-line scalar that
  // broke the generated .loopover.yml with a stray top-level line.
  it("quotes a model value containing an embedded newline", () => {
    const model = "claude 3.7\nignore_findings true";
    const output = formStateToYaml({ gate: { aiReview: { model } } });
    expect(output).toBe(
      [HEADER, "gate:", "  aiReview:", `    model: ${JSON.stringify(model)}`].join("\n"),
    );
    // The serialized value must stay on a single line -- no stray line beyond the 4 expected ones.
    expect(output.split("\n")).toHaveLength(4);
  });

  it("quotes a model value containing a carriage return", () => {
    const model = "claude\r3.7";
    expect(formStateToYaml({ gate: { aiReview: { model } } })).toBe(
      [HEADER, "gate:", "  aiReview:", `    model: ${JSON.stringify(model)}`].join("\n"),
    );
  });

  // Regression (#8022): rees.analyzers overrides never reached the preview at all, since this module
  // declared its own narrower GeneratorFormState duplicate with no `rees` field.
  describe("review.enrichment (REES analyzer overrides, #8022)", () => {
    it("serializes rees.analyzers overrides as a review.enrichment map", () => {
      const state: GeneratorFormState = {
        rees: { analyzers: { "deep-nesting": true, "error-swallow": false } },
      };
      expect(formStateToYaml(state)).toBe(
        [
          HEADER,
          "review:",
          "  enrichment:",
          "    deep-nesting: true",
          "    error-swallow: false",
        ].join("\n"),
      );
    });

    it("sorts analyzer entries alphabetically regardless of insertion order", () => {
      const state: GeneratorFormState = {
        rees: { analyzers: { "zebra-analyzer": true, "alpha-analyzer": true } },
      };
      expect(formStateToYaml(state)).toBe(
        [
          HEADER,
          "review:",
          "  enrichment:",
          "    alpha-analyzer: true",
          "    zebra-analyzer: true",
        ].join("\n"),
      );
    });

    it("omits the review.enrichment block when rees.analyzers is empty", () => {
      expect(formStateToYaml({ rees: { analyzers: {} } })).toBe(HEADER);
    });

    it("omits the review.enrichment block when rees is entirely unset", () => {
      expect(formStateToYaml({ rees: undefined })).toBe(HEADER);
    });

    it("keeps a false override in the output rather than treating it as unset", () => {
      const state: GeneratorFormState = { rees: { analyzers: { "secret-scan": false } } };
      expect(formStateToYaml(state)).toBe(
        [HEADER, "review:", "  enrichment:", "    secret-scan: false"].join("\n"),
      );
    });

    it("renders both gate.aiReview and review.enrichment when both are configured", () => {
      const state: GeneratorFormState = {
        gate: { aiReview: { provider: "anthropic" } },
        rees: { analyzers: { "deep-nesting": true } },
      };
      expect(formStateToYaml(state)).toBe(
        [
          HEADER,
          "gate:",
          "  aiReview:",
          "    provider: anthropic",
          "review:",
          "  enrichment:",
          "    deep-nesting: true",
        ].join("\n"),
      );
    });
  });
});
