// Config-generator YAML preview serializer (#2210, part of #1683). Pure form-state -> `.loopover.yml`
// text builder — the reviewable-output half of the config generator; field-group panels (#2208 and
// siblings) own collecting GeneratorFormState, this module only turns it into text. Key names and
// nesting match the real manifest schema (packages/loopover-engine/src/focus-manifest.ts's
// gateConfigToJson `gate.aiReview` shape and `review.enrichment` shape, both documented in this repo's
// own root .loopover.yml.example) — no parallel schema. Every field is optional so a fresh/partial form
// never produces invalid output; unset keys are omitted entirely. The generated header names the
// `.loopover.yml` filename.
//
// GeneratorFormState is re-exported from config-generator-form-state.ts (#8022) rather than declared a
// second time here -- ConfigGeneratorPanel collects the one richer state object field-group panels
// (including ReesAnalyzerFieldGroup) write to, and this module needs the same shape, not a structurally-
// compatible-but-narrower duplicate that silently can't see fields like `rees`.
import type { GeneratorFormState } from "./config-generator-form-state";

export type {
  AiCombineStrategy,
  AiProvider,
  GeneratorFormState,
  GeneratorGateAiReviewState,
} from "./config-generator-form-state";

const YAML_HEADER = "# .loopover.yml — generated by the config generator";

/** Plain-scalar YAML value needs quoting when it would otherwise be ambiguous (a YAML special
 *  character, an embedded line break, leading/trailing whitespace, or the empty string). Model names
 *  are free text, so this is a real correctness need, not defensive-for-its-own-sake. `value.trim()`
 *  only catches whitespace at the edges, so an embedded `\n`/`\r` must be flagged explicitly (#7786)
 *  or `formStateToYaml` would emit it as a raw, file-breaking multi-line scalar. */
function yamlScalar(value: string): string {
  const needsQuote =
    value === "" || value.trim() !== value || /[\n\r:#[\]{}&*!|>'"%@`,]/.test(value);
  return needsQuote ? JSON.stringify(value) : value;
}

function yamlLine(indent: number, key: string, value: string): string {
  return `${"  ".repeat(indent)}${key}: ${yamlScalar(value)}`;
}

// Analyzer names come from the app's own REES_ANALYZERS catalog (validated GeneratorReesState keys), never
// free text, so a boolean value needs no scalar-quoting -- `true`/`false` are unambiguous YAML literals.
function yamlBooleanLine(indent: number, key: string, value: boolean): string {
  return `${"  ".repeat(indent)}${key}: ${value}`;
}

/** Serializes the `gate.aiReview` and `review.enrichment` slices of GeneratorFormState into `.loopover.yml`
 *  text, omitting every unset field/block so the preview is always valid YAML (including the empty-state
 *  case). `review.enrichment` mirrors `state.rees.analyzers` directly (an overrides-only map, matching the
 *  real manifest field's own shape) rather than going through `reesAnalyzersManifestPatch`'s exact-list
 *  output, which serializes the REES_ANALYZERS env var, a different representation of the same overrides
 *  for a different consumer. */
export function formStateToYaml(state: GeneratorFormState): string {
  const aiReview = state.gate?.aiReview;
  const aiReviewLines: string[] = [];
  if (aiReview?.combine) aiReviewLines.push(yamlLine(2, "combine", aiReview.combine));
  if (aiReview?.provider) aiReviewLines.push(yamlLine(2, "provider", aiReview.provider));
  if (aiReview?.model) aiReviewLines.push(yamlLine(2, "model", aiReview.model));

  const enrichmentEntries = Object.entries(state.rees?.analyzers ?? {}).sort(([a], [b]) =>
    a.localeCompare(b),
  );

  const lines = [YAML_HEADER];
  if (aiReviewLines.length > 0) {
    lines.push("gate:", "  aiReview:", ...aiReviewLines);
  }
  if (enrichmentEntries.length > 0) {
    lines.push(
      "review:",
      "  enrichment:",
      ...enrichmentEntries.map(([name, enabled]) => yamlBooleanLine(2, name, enabled)),
    );
  }
  return lines.join("\n");
}
